## Assignment_8

-------------
### 1. Write a Python Program to Add Two Matrices?


In [1]:
import numpy as np

# Definng the matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Adding the matrices
C = A + B

print("Result of addition:\n", C)

Result of addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


-------------
### 2. Write a Python Program to Multiply Two Matrices?

In [4]:
#method 1
import numpy as np

# Defining the matrices
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Multiplication using numpy.dot()
C = np.dot(A, B)

print("Result of multiplication:\n", C)

Result of multiplication:
 [[ 58  64]
 [139 154]]


In [9]:
# method 2 Using the @ operator
import numpy as np

# Defining the matrices
A = np.array([[1, 2, 3],
                [4, 5, 6]])

B = np.array([[7, 8],
                [9, 10],
                [11, 12]])

# Multiplication using @ operator
C = A @ B

print("Result of multiplication:\n", C)

Result of multiplication:
 [[ 58  64]
 [139 154]]


In [8]:
#method 3
import numpy as np

#size of matrix A is 2x3 
A = np.array([[1, 2, 3],
              [4, 5, 6]])
#size of matrix B is 3x2
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

#creating a matrix to store the result equal to size of AxB
result = np.zeros((A.shape[0], B.shape[1]))#size of result matrix is 2x2

for i in range(A.shape[0]):#iterating by row of A
    for j in range(B.shape[1]):#iterating by coloum by B
        for k in range(A.shape[1]):#iterating by rows of B
            result[i][j] += A[i][k] * B[k][j]

print("Result of multiplication:\n", result)

Result of multiplication:
 [[ 58.  64.]
 [139. 154.]]


-------------
### 3. Write a Python Program to Transpose a Matrix?

In [17]:
#method 1 : using numpy library
import numpy as np

# Defining the matrix
matrix = np.array([[1,2],
                [3,4],
                [5,6]])

transpose = matrix.T

print("Transpose of matrix:")
print(transpose)

Transpose of matrix:
[[1 3 5]
 [2 4 6]]


In [10]:
#method 2 : Transposing a matrix using a nested loop

X = [[1,2],
    [3,4],
    [5,6]]

result = [[0,0,0],
         [0,0,0]]

# iterating through rows
for i in range(len(X)):
   # iterating through columns
   for j in range(len(X[0])):
        result[j][i] = X[i][j]

for r in result:
    print(r)

[1, 3, 5]
[2, 4, 6]


------------------
### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [20]:
try:
    sentance = input("Enter the words: ")
    print(f"input text: {sentance}")
    words = [word.lower() for word in sentance.split()]
    words.sort()
    
    print(f"Sorted order of words: {words}")
    joined_words = " ".join(words)
    print(f"Joined words: {joined_words}")

except Exception as e:
    print(e)

input text:  Write a Python Program to Sort Words in Alphabetic Order?
Sorted order of words: ['a', 'alphabetic', 'in', 'order?', 'program', 'python', 'sort', 'to', 'words', 'write']
Joined words: a alphabetic in order? program python sort to words write


-----------------
### 5. Write a Python Program to Remove Punctuation From a String?

In [24]:
#method 1
import string

def remove_punctuation(text):
    # Create a translation table using string.punctuation
    translator = str.maketrans("", "", string.punctuation)
    # Remove punctuation using translate() method
    text_without_punct = text.translate(translator)
    
    return text_without_punct

text = "Hello! How are you? I'm doing well, thank you."
text_without_punct = remove_punctuation(text)
print("Text without punctuation:", text_without_punct)


Text without punctuation: Hello How are you Im doing well thank you


In [26]:
#method 2
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

string = text = "Hello! How are you? I'm doing well, thank you."

outputString = ""

for char in string:
    if char not in punctuations:
        outputString += char
        
print("Text without punctuation:",outputString)

Text without punctuation: Hello How are you Im doing well thank you
