# Assignment_13


### 1. Write a program that calculates and prints the value according to the given formula:
- Q = Square root of [(2 C D)/H]<br>
Following are the fixed values of C and H:<br>
C is 50. H is 30.<br>

- D is the variable whose values should be input to your program in a comma-separated sequence.<br>


Example<br>
- Let us assume the following comma separated input sequence is given to the program:<br>
100,150,180<br>
The output of the program should be:<br>
18,22,24

In [2]:
import math

def calculate_formula(args):
    c = 50;h = 30
    result = []
    for d in args:
        result.append(int(math.sqrt((2*c*int(d))/h)))
    return result
    
csv_in = list(input("Enter comma separated numbers input: ").split(','))
calculate_formula(csv_in)

[18, 22, 24]

### 2. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

In [7]:
import numpy as np

X = int(input("Enter the value of X: "))
Y = int(input("Enter the value of Y: "))
arr = np.zeros((X, Y), dtype=int)

for i in range(X):
    for j in range(Y):
        arr[i][j] = i * j

print(arr)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


### 3. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

In [13]:
words = input("Enter a comma-separated sequence of words: ")

words_list = words.split(",")
words_list.sort()
sorted_words = ",".join(words_list)
print(sorted_words)

apple,ball,cat,dog,host,mango,mouse,orange


### 4. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

In [4]:
def remove_duplicates_and_sort_words(input_string):
    
    words = input_string.split()
    unique_words = list(set(words))
    sorted_words = sorted(unique_words)
    return ' '.join(sorted_words)

# input sentence : hello world, hello hari, hello ravi, hello world , Hello world!
input_sequence = input("Enter a sequence of whitespace separated words: ")
result = remove_duplicates_and_sort_words(input_sequence)
print("Result:", result)

Result: , Hello hari, hello ravi, world world! world,


### 5. Write a program that accepts a sentence and calculate the number of letters and digits.

In [8]:
#Method 1
def count_letters_and_digits_1(sentence):
    letters = 0
    digits = 0

    for char in sentence:
        if char.isalpha():
            letters += 1
        elif char.isdigit():
            digits += 1

    return letters, digits

# input sentence : hello world! 123456!
sentence = input("Enter a sentence: ")
letter_count, digit_count = count_letters_and_digits_1(sentence)
print("Number of letters:", letter_count)
print("Number of digits:", digit_count)

Number of letters: 10
Number of digits: 6


In [9]:
#Method 2
def count_letters_and_digits_2(sentence):    
    words = input("Enter a sentence: ")
    letters = 0
    digits = 0
    for c in words:
        if (ord(c) >= ord('a') and ord(c) <= ord('z')) or (ord(c) >= ord('A') and ord(c) <= ord('Z')):
            letters += 1
        elif ord(c) >= ord('0') and ord(c) <= ord('9'):
            digits += 1
    return letters, digits
            
# input sentence : hello world! 123456!
sentence = input("Enter a sentence: ")
letter_count, digit_count = count_letters_and_digits_2(sentence)
print("Number of letters:", letter_count)
print("Number of digits:", digit_count)

Number of letters: 10
Number of digits: 6


### 6. A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

In [21]:
def check_password_validity(password):
    #password length >= 8 characters
    if len(password) < 8:
        raise ValueError("Password should be at least 8 characters long")

    # Checking at least one uppercase, one lowercase, and one digit
    has_uppercase = False
    has_lowercase = False
    has_digit = False

    for char in password:
        if char.isupper():
            has_uppercase = True
        elif char.islower():
            has_lowercase = True
        elif char.isdigit():
            has_digit = True

    if not (has_uppercase and has_lowercase and has_digit):
        raise ValueError("Password should contain at least one uppercase letter, one lowercase letter, and one digit")


#input from user
password = input("Enter your password: ")

try:
    # Checking validity of the password
    check_password_validity(password)
    print(f'Password "{password}" is valid')
except ValueError as error:
    print(f'Password "{password}" is not valid Error:', str(error))


Password "r4Fe444@j3" is valid


In [24]:
#Test Case 2
password = "r46e444j"
check_password_validity(password)

try:
    # Checking validity of the password
    check_password_validity(password)
    print(f'Password "{password}" is valid')
except ValueError as error:
    print(f'Password "{password}" is not valid Error:', str(error))

ValueError: Password should contain at least one uppercase letter, one lowercase letter, and one digit

In [26]:
#Test Case 3
password = "19hari"
check_password_validity(password)

if validity:
    print(f'Password "{password}" is valid')
else:
    print(f'Password "{password}", is not valid')

ValueError: Password should be at least 8 characters long